name: Application
description: Apply to receive a delegation from the delegation DAO
labels: Application
body:
  - type: markdown
    attributes:
      value: |
        Thank you for applying to the Bitsong Delegation program. Please take your time and give us as much detail as possible to ensure a good evaluation of your application..
        
        ---
    
  - type: input
    id: validator
    attributes:
      label: Validator address 
      description: "Please provide the address of your validator "
      placeholder: "bitsongvaloper1c5p4sqgz5jslpywsk5c0nasqqjfucv9lvjlnry"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "On Chain Data"
      description: Please confirm that the basic information (validator contact information (website, twitter, telegram, etc.), details & avatar/logo) is set on chain
      options:
        - label: I confirm to have set my validator information on chain
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact information
      description: "Please provide a possibility to contact you"
      placeholder: "SAKURA#0129/@STAVRRR/cloname@ya.ru"
    validations:
      required: true
  - type: dropdown
    id: categories
    attributes:
      label: "Application categories"
      description: "Uptime, Commission restake, Self delegation, None core development, Running relayers, Running an archive node, Running an public rpc/api"
      multiple: true
      options:
        - Uptime
        - Commission restake
        - Self delegation
        - Participation in the BitSong ecosystem 
        - Core development
        - None core development
        - Running relayers
        - Running an archive node 
        - Running an public rpc/api 
    validations:
      required: true      
  - type: textarea
    id: details
    attributes:
      label: Details
      description: We have been validating mainnets and testnets since early 2020. And so our team provides RPC projects, IBC relayers in the right networks, the development of various tools for validators. We develop monitoring.
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: Our goal is to become a major staking provider in Europe and Asia. We develop partnerships and develop diversified.
  - type: textarea
    id: tiemtable
    attributes:
      label: Timetable
      description: If the delegation approves, we will promote your project in our communities as actively as possible. Because we will be interested in it. In 1-2 months, there will be tangible results.
      💻 Our github https://github.com/obajay
