name: Application
description: Apply to receive a delegation from the delegation DAO
labels: Application
body:
  - type: markdown
    attributes:
      value: |
        Thank you for applying to the Bitsong Delegation program. Please take your time and give us as much detail as possible to ensure a good evaluation of your application..
        
        ---
    
  - type: input
    id: validator
    attributes:
      label: Validator address
      description: "Please provide the address of your validator "
      placeholder: "bitsongvaloper139dppl6gyerq8yaweksajut3urwyygsz7r4ej4"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "On Chain Data"
      description: Please confirm that the basic information (validator contact information (website, twitter, telegram, etc.), details & avatar/logo) is set on chain
      options:
        - label: I confirm to have set my validator information on chain
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact information
      description: "Please provide a possibility to contact you"
      placeholder: "Discord/Telegram/Mail"
    validations:
      required: true
  - type: dropdown
    id: categories
    attributes:
      label: "Application categories"
      description: "Please provide all categories you want to apply for. Each application automatically qualifies for the uptime and self-delegation categories"
      multiple: true
      options:
        - Uptime
        - Commission restake
        - Self delegation
        - Participation in the BitSong ecosystem 
        - Core development
        - None core development
        - Running relayers
        - Running an archive node 
        - Running an public rpc/api 
    validations:
      required: true      
  - type: My website https://web3validator.info/ ,and validator portfolio https://github.com/cybernekit/SomethingAboutMyself/blob/main/web34ever-self-identity.md
    id: details
    attributes:
      label: Details
      description: Please provide all the information in regards to your selected application categories
    validations:
      required: true
  - type: Commission restake (https://www.mintscan.io/bitsong/txs/DFAD818DB7BA0E782AA2DA1172713004B22CC49CFD2EB4817FE838D6CFDD1DB2, https://www.mintscan.io/bitsong/validators/bitsongvaloper139dppl6gyerq8yaweksajut3urwyygsz7r4ej4),Participation in the BitSong ecosystem (Governance),None core development (Self-made bot that not only warns that the validator is already in jail but pings you when your validator start to skiping blocks to keep you out of jail: https://t.me/BitsongUpTime_bot ), Running an public rpc/api (http://65.108.66.34:26257/) 
    id: goals
    attributes:
      label: Goals
      description: What are your goals that you want to achieve with your contribution??
  - type: Web3 validator provides much more than security! We are actively participate in the development of the Network and Community by providing informational, technical and humanitarian support! 
    id: tiemtable
    attributes:
      label: Timetable
      description: If there is a timetable for the contribution, please feel free to share it here. It is definitely recommended, especially for long-term contributions.
